# Labeler configuration for automatic PR labeling
# Based on file paths to categorize changes

# API/Backend changes
api:
  - changed-files:
      - any-glob-to-any-file: "src/api/**"
  - changed-files:
      - any-glob-to-any-file: "libs/backend/**"

# Frontend changes
frontend:
  - changed-files:
      - any-glob-to-any-file: "src/frontend/**"
  - changed-files:
      - any-glob-to-any-file: "components/**"

# Infrastructure/DevOps
infrastructure:
  - changed-files:
      - any-glob-to-any-file: ".github/**"
  - changed-files:
      - any-glob-to-any-file: "docker-compose*.yml"
  - changed-files:
      - any-glob-to-any-file: "Makefile"

# Testing
testing:
  - changed-files:
      - any-glob-to-any-file: "tests/**"
  - changed-files:
      - any-glob-to-any-file: "**/*test*.js"
  - changed-files:
      - any-glob-to-any-file: "**/*test*.ts"

# Documentation
documentation:
  - changed-files:
      - any-glob-to-any-file: "docs/**"
  - changed-files:
      - any-glob-to-any-file: "README.md"
  - changed-files:
      - any-glob-to-any-file: "**/*.md"

# Dependencies
dependencies:
  - changed-files:
      - any-glob-to-any-file: "package.json"
  - changed-files:
      - any-glob-to-any-file: "requirements*.txt"
