name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
version-template: "$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "dependencies"
      - "maintenance"
  - title: "📚 Documentation"
    labels:
      - "documentation"
      - "docs"
  - title: "🧪 Testing"
    labels:
      - "testing"
      - "tests"
  - title: "🏗️ Infrastructure"
    labels:
      - "infrastructure"
      - "devops"
      - "ci/cd"
  - title: "🎨 Frontend"
    labels:
      - "frontend"
      - "ui"
      - "ux"
  - title: "⚙️ Backend"
    labels:
      - "api"
      - "backend"
  - title: "📊 Analytics"
    labels:
      - "analytics"
      - "tracking"
      - "metrics"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
template: |
  ## Changes

  $CHANGES

  ## Deployment
  - This release will automatically deploy **${{ env.SERVICE_NAME }}** to **production** (if changes detected)
  - Deployed with version tag: `"$RESOLVED_VERSION"`
  - Stage environment already has these changes (deployed on merge to main)
  ${{ env.SERVICE_SPECIFIC_INFO }}

  ## Release Information
  - **Service**: ${{ env.SERVICE_NAME }}
  - **Version**: `"$RESOLVED_VERSION"` (date-based versioning)
