name: "Set Version"
description: "Sets a date-based version with increment for multiple releases per day"
inputs:
  service:
    description: "Service name for service-specific versioning"
    required: false
    default: "api-ui"
outputs:
  version:
    description: "The date-based version (YY.MM.DD.N/service)"
    value: ${{ steps.set-version.outputs.version }}
  commit-sha:
    description: "The commit SHA for this context"
    value: ${{ steps.set-version.outputs.commit-sha }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: set-version
      run: |
        # Get current date in YY.MM.DD format (removed 20 prefix)
        DATE=$(date +%y.%m.%d)
        SERVICE="${{ inputs.service }}"

        # Get commit SHA (only for main branch pushes, no PR handling)
        COMMIT_SHA="${{ github.sha }}"

        # Get the latest release for today (global increment, not service-specific)
        # Look for any tag matching the date pattern: YY.MM.DD.N/service
        LATEST_TAG=$(git tag -l "$DATE.*" | sort -V | tail -1 || echo "")

        if [ -z "$LATEST_TAG" ]; then
          # No releases today, start with .1
          VERSION="$DATE.1/$SERVICE"
        else
          # Extract the increment number and add 1
          # Format: YY.MM.DD.N/service -> extract N
          INCREMENT=$(echo "$LATEST_TAG" | cut -d'.' -f4 | cut -d'/' -f1)
          if [ -z "$INCREMENT" ]; then
            VERSION="$DATE.1/$SERVICE"
          else
            NEW_INCREMENT=$((INCREMENT + 1))
            VERSION="$DATE.$NEW_INCREMENT/$SERVICE"
          fi
        fi

        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "commit-sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
        echo "Set version to: $VERSION for service: $SERVICE"
        echo "Set commit SHA to: $COMMIT_SHA"
        echo "Latest tag found: $LATEST_TAG"
        echo "Date: $DATE"
