name: "Set Version"
description: "Sets an incremental version number for each service"
inputs:
  service:
    description: "Service name for service-specific versioning"
    required: false
    default: "api-ui"
outputs:
  version:
    description: "The incremental version number"
    value: ${{ steps.set-version.outputs.version }}
  commit-sha:
    description: "The commit SHA for this context"
    value: ${{ steps.set-version.outputs.commit-sha }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: set-version
      run: |
        SERVICE="${{ inputs.service }}"

        # Get commit SHA (only for main branch pushes, no PR handling)
        COMMIT_SHA="${{ github.sha }}"

        # Get the latest release for this service
        # Look for tags matching the service pattern: service-number
        # Extract all version numbers for this service and find the highest
        HIGHEST_VERSION=$(git tag -l "$SERVICE-*" | sed "s|$SERVICE-||" | sort -n | tail -1 || echo "")

        if [ -z "$HIGHEST_VERSION" ]; then
          # No releases for this service yet, start with 1
          VERSION="1"
        else
          # Increment the highest version number
          VERSION=$((HIGHEST_VERSION + 1))
        fi

        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "commit-sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
        echo "Set version to: $VERSION for service: $SERVICE"
        echo "Set commit SHA to: $COMMIT_SHA"
        echo "Highest version found for $SERVICE: $HIGHEST_VERSION"
        echo "Service: $SERVICE"
