name: "Set Version"
description: "Sets a date-based version with increment for multiple releases per day"
inputs:
  service:
    description: "Service name for service-specific versioning"
    required: false
    default: "main"
  event-name:
    description: "GitHub event name (push, pull_request, etc.)"
    required: false
    default: "push"
outputs:
  version:
    description: "The date-based version (YYYY.MM.DD.N)"
    value: ${{ steps.set-version.outputs.version }}
  commit-sha:
    description: "The commit SHA for this context"
    value: ${{ steps.set-version.outputs.commit-sha }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: set-version
      run: |
        # Get current date in YYYY.MM.DD format
        DATE=$(date +%Y.%m.%d)
        SERVICE="${{ inputs.service }}"

        # Get commit SHA based on event context
        if [ "${{ inputs.event-name }}" = "pull_request" ]; then
          COMMIT_SHA="${{ github.event.pull_request.head.sha }}"
        else
          COMMIT_SHA="${{ github.sha }}"
        fi

        # Get the latest release for today for this service to determine increment
        if [ "$SERVICE" = "main" ]; then
          LATEST_TAG=$(git tag -l "api-ui-$DATE.*" | sort -V | tail -1 || echo "")
        else
          LATEST_TAG=$(git tag -l "$SERVICE-$DATE.*" | sort -V | tail -1 || echo "")
        fi

        if [ -z "$LATEST_TAG" ]; then
          # No releases today for this service, start with .1
          if [ "$SERVICE" = "main" ]; then
            VERSION="api-ui-$DATE.1"
          else
            VERSION="$SERVICE-$DATE.1"
          fi
        else
          # Extract the increment number and add 1
          if [ "$SERVICE" = "main" ]; then
            INCREMENT=$(echo "$LATEST_TAG" | cut -d'.' -f4)
            if [ -z "$INCREMENT" ]; then
              VERSION="api-ui-$DATE.1"
            else
              NEW_INCREMENT=$((INCREMENT + 1))
              VERSION="api-ui-$DATE.$NEW_INCREMENT"
            fi
          else
            # For non-main services, extract from service-prefixed tag
            INCREMENT=$(echo "$LATEST_TAG" | cut -d'.' -f4)
            if [ -z "$INCREMENT" ]; then
              VERSION="$SERVICE-$DATE.1"
            else
              NEW_INCREMENT=$((INCREMENT + 1))
              VERSION="$SERVICE-$DATE.$NEW_INCREMENT"
            fi
          fi
        fi

        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "commit-sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
        echo "Set version to: $VERSION for service: $SERVICE"
        echo "Set commit SHA to: $COMMIT_SHA"
        echo "Latest tag found: $LATEST_TAG"
        echo "Date: $DATE"
