name: "Set Version"
description: "Sets a date-based version with increment for multiple releases per day"
outputs:
  version:
    description: "The date-based version (YYYY.MM.DD.N)"
    value: ${{ steps.set-version.outputs.version }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: set-version
      run: |
        # Get current date in YYYY.MM.DD format
        DATE=$(date +%Y.%m.%d)

        # Get the latest release for today to determine increment
        LATEST_TAG=$(git tag -l "$DATE.*" | sort -V | tail -1)

        if [ -z "$LATEST_TAG" ]; then
          # No releases today, start with .1
          VERSION="$DATE.1"
        else
          # Extract the increment number and add 1
          INCREMENT=$(echo "$LATEST_TAG" | cut -d'.' -f4)
          NEW_INCREMENT=$((INCREMENT + 1))
          VERSION="$DATE.$NEW_INCREMENT"
        fi

        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Set version to: $VERSION"
