name: "Set Version"
description: "Sets a semver-based version with patch increment for each service"
inputs:
  service:
    description: "Service name for service-specific versioning"
    required: false
    default: "api-ui"
outputs:
  version:
    description: "The semver-based version (X.Y.Z)"
    value: ${{ steps.set-version.outputs.version }}
  commit-sha:
    description: "The commit SHA for this context"
    value: ${{ steps.set-version.outputs.commit-sha }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: set-version
      run: |
        SERVICE="${{ inputs.service }}"

        # Get commit SHA (only for main branch pushes, no PR handling)
        COMMIT_SHA="${{ github.sha }}"

        # Get the latest release for this service
        # Look for tags matching the service pattern: X.Y.Z/service
        LATEST_TAG=$(git tag -l "*$SERVICE" | sort -V | tail -1 || echo "")

        if [ -z "$LATEST_TAG" ]; then
          # No releases for this service yet, start with 1.0.0
          VERSION="1.0.0"
        else
          # Extract the version number (remove /service suffix)
          VERSION_ONLY=$(echo "$LATEST_TAG" | sed "s|/$SERVICE||")
          
          # Parse semver components
          MAJOR=$(echo "$VERSION_ONLY" | cut -d'.' -f1)
          MINOR=$(echo "$VERSION_ONLY" | cut -d'.' -f2)
          PATCH=$(echo "$VERSION_ONLY" | cut -d'.' -f3)
          
          # Increment patch version
          NEW_PATCH=$((PATCH + 1))
          VERSION="$MAJOR.$MINOR.$NEW_PATCH"
        fi

        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "commit-sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
        echo "Set version to: $VERSION for service: $SERVICE"
        echo "Set commit SHA to: $COMMIT_SHA"
        echo "Latest tag found: $LATEST_TAG"
        echo "Service: $SERVICE"
