name: "Analytics Release Drafter"
description: "Creates or updates analytics service release draft using release-drafter"
inputs:
  version:
    description: "Version for the release"
    required: true
  commit-sha:
    description: "Commit SHA for the release"
    required: true
  github-token:
    description: "GitHub token for API access"
    required: true
outputs:
  release-id:
    description: "ID of the created/updated release"
    value: ${{ steps.release-drafter.outputs.id }}
  release-name:
    description: "Name of the release"
    value: ${{ steps.release-drafter.outputs.name }}
  release-tag:
    description: "Tag of the release"
    value: ${{ steps.release-drafter.outputs.tag_name }}
runs:
  using: "composite"
  steps:
    - name: Run Analytics Release Drafter
      id: release-drafter
      uses: release-drafter/release-drafter@v6
      with:
        config-name: "release-drafter-analytics.yml"
        version: ${{ inputs.version }}
        name: "Analytics Release ${{ inputs.version }} 📊"
        tag: "${{ inputs.version }}/analytics"
        header: "Commit: ${{ inputs.commit-sha }}"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
