name: "Release Deployment"

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  # Debug deployment context
  debug-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Debug - Deployment Context
        run: |
          echo "🔍 DEBUG: Deployment Workflow Context"
          echo "===================================="
          echo "Event: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "Release Tag: ${{ github.event.release.tag_name }}"
          echo "Release Name: ${{ github.event.release.name }}"
          echo "Release ID: ${{ github.event.release.id }}"
          echo "Release Draft: ${{ github.event.release.draft }}"
          echo "Release Prerelease: ${{ github.event.release.prerelease }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "===================================="

  # Deploy main service (API + UI)
  deploy-main-service:
    if: endsWith(github.event.release.tag_name, '/api-ui')
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Main Service Deployment
        run: |
          echo "🚀 DEPLOYING API + UI TO PRODUCTION"
          echo "=================================="
          echo "Release Tag: ${{ github.event.release.tag_name }}"
          echo "Release Name: ${{ github.event.release.name }}"
          echo "Services: API + UI"
          echo "Environment: production"
          echo "Timestamp: $(date)"
          echo "=================================="
          echo "✅ Main service deployment completed successfully!"

  # Deploy analytics service
  deploy-analytics-service:
    if: endsWith(github.event.release.tag_name, '/analytics')
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Analytics Service Deployment
        run: |
          echo "📊 DEPLOYING ANALYTICS SERVICE TO PRODUCTION"
          echo "=========================================="
          echo "Release Tag: ${{ github.event.release.tag_name }}"
          echo "Release Name: ${{ github.event.release.name }}"
          echo "Services: Analytics"
          echo "Environment: production"
          echo "Timestamp: $(date)"
          echo "=========================================="
          echo "✅ Analytics service deployment completed successfully!"

  # Notify deployment completion
  notify-deployment:
    needs: [debug-deployment, deploy-main-service, deploy-analytics-service]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify deployment completion
        run: |
          echo "📢 DEPLOYMENT NOTIFICATION"
          echo "=========================="
          echo "Release Tag: ${{ github.event.release.tag_name }}"
          echo "Release Name: ${{ github.event.release.name }}"
          echo "Status: ${{ job.status }}"
          if [[ "${{ github.event.release.tag_name }}" == */api-ui ]]; then
            echo "Services: API + UI"
          elif [[ "${{ github.event.release.tag_name }}" == */analytics ]]; then
            echo "Services: Analytics"
          fi
          echo "Environment: production"
          echo "=========================="
