name: "Release Deployment"

on:
  push:
    tags:
      - "2025.*" # Main service tags (API + UI)
      - "analytics-*" # Analytics service tags

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  # Deploy main service (API + UI)
  deploy-main-service:
    if: startsWith(github.ref_name, '2025.')
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Main Service Deployment
        run: |
          echo "🚀 DEPLOYING API + UI TO PRODUCTION"
          echo "=================================="
          echo "Release Tag: ${{ github.ref_name }}"
          echo "Services: API + UI"
          echo "Environment: production"
          echo "Timestamp: $(date)"
          echo "=================================="
          echo "✅ Main service deployment completed successfully!"

  # Deploy analytics service
  deploy-analytics-service:
    if: startsWith(github.ref_name, 'analytics-')
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Analytics Service Deployment
        run: |
          echo "📊 DEPLOYING ANALYTICS SERVICE TO PRODUCTION"
          echo "=========================================="
          echo "Release Tag: ${{ github.ref_name }}"
          echo "Services: Analytics"
          echo "Environment: production"
          echo "Timestamp: $(date)"
          echo "=========================================="
          echo "✅ Analytics service deployment completed successfully!"

  # Notify deployment completion
  notify-deployment:
    needs: [deploy-main-service, deploy-analytics-service]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify deployment completion
        run: |
          echo "📢 DEPLOYMENT NOTIFICATION"
          echo "=========================="
          echo "Release: ${{ github.ref_name }}"
          echo "Status: ${{ job.status }}"
          if [[ "${{ github.ref_name }}" == 2025.* ]]; then
            echo "Services: API + UI"
          elif [[ "${{ github.ref_name }}" == analytics-* ]]; then
            echo "Services: Analytics"
          fi
          echo "Environment: production"
          echo "=========================="
