name: "Release Drafter"
description: "Creates or updates a release draft using release-drafter with common configuration"
inputs:
  service:
    description: "Service name (main, analytics, etc.)"
    required: true
  config-name:
    description: "Name of the release-drafter config file"
    required: true
  version:
    description: "Version for the release"
    required: true
  commit-sha:
    description: "Commit SHA for the release"
    required: true
  name-prefix:
    description: "Prefix for the release name (e.g., 'Release', 'Analytics Release')"
    required: true
  name-emoji:
    description: "Emoji for the release name"
    required: true
  tag-prefix:
    description: "Prefix for the tag (empty for main service, 'analytics-' for analytics, etc.)"
    required: false
    default: ""
  github-token:
    description: "GitHub token for API access"
    required: true
  service-name:
    description: "Human-readable service name for release notes"
    required: false
    default: "Main Service"
  service-specific-info:
    description: "Additional service-specific deployment information"
    required: false
    default: ""
outputs:
  release-id:
    description: "ID of the created/updated release"
    value: ${{ steps.release-drafter.outputs.id }}
  release-name:
    description: "Name of the release"
    value: ${{ steps.release-drafter.outputs.name }}
  release-tag:
    description: "Tag of the release"
    value: ${{ steps.release-drafter.outputs.tag_name }}
runs:
  using: "composite"
  steps:
    - name: Run Release Drafter
      id: release-drafter
      uses: release-drafter/release-drafter@v6
      with:
        config-name: ${{ inputs.config-name }}
        version: ${{ inputs.version }}
        name: "${{ inputs.name-prefix }} ${{ inputs.version }} ${{ inputs.name-emoji }}"
        tag: "${{ inputs.tag-prefix }}${{ inputs.version }}"
        header: "Commit: ${{ inputs.commit-sha }}"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SERVICE_NAME: ${{ inputs.service-name }}
        SERVICE_SPECIFIC_INFO: ${{ inputs.service-specific-info }}
